### ISSUE TITLE
PR workflow megaticket

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#1319]
- [x] Improve the error message when `pr.load` isn't issued in (or provided) an empty namespace. #1311
- [x] `pr.create` output could mention that `pr.load` needs an empty namespace #1318
- [x] Merge bug #1250/#1263
- [x] Hang on push #1276/#1279
- [x] Allow add/update to create aliases #1253/#1254
- [x] The command that gets pasted at the top of the PR output is both indented and in backticks. #1260
- [x] Hide useless numbers from `pr.create` output #1203/#1259
- [x] The command that gets pasted at the top of the PR output is both indented and in backticks.

* [x] Docs / tutorial for PR process 
  * maybe we choose a nice example from our dogfooding 
  * partly blocked on any of these improvements

Bikeshedding:
* [x] The nomenclature "Pull Request" is an artifact of some other tool (github).
* [x] Especially "PR" is unclear. Like, what does it mean? You don't know unless you already know the github workflow. `pull-request.create` `pr.create`

Needs design:
* [ ] Ability to attach metadata to namespaces like `CreationDate`, etc
* [ ] I lost track of the next steps for the PR workflow #1314
  * May depend on attaching metadata to namespaces
  * For comparison: `git` keeps some state around, and when you type `git status` reminds you of relevant commands, like "you are working on a merge, use <blah> to abort."
  * `note` RFC #1266
* [x] `push` and `pull` (which are used by pr.create) are sluggish, don't do any intelligent syncing #1281 — 3/4 done in #1293 and #1317(has bugs)

Not strictly PR related:
- [ ] Fix help for `find`. The help for `find foo` is wrong, or the implementation of `find` is wrong. It says it only looks in the current namespace, but it actually looks everywhere. #1313
- [ ] should have a display handler for authors and license #1312
- [ ] feedback on `unlink` is bad if one of the names is invalid
- [x] no explicit error when `link` argument doesn't exist #1244
- [x] `debug.file` command to get hashes for stuff in latest typechecked file #1316 

TBD/Blocked:
* [x] view command should probably use suffix based resolution #1241 / #1298
* [x] Hide `push` and `pull` output unless there's an error, just give a spinner (may have to not use shellmet)
  — #1293 reduces the output; would still need to not use shellmet if we wanted to reduce further.  recommend we parse the git output (messy / error-prone) to be able to give useful errors back to the user in exceptional cases.

Usability:
* [ ] It's not at all clear how to go through the PR process. Some kind of guidance or hand-holding would be nice. Even if it's just a Doc somewhere.
* [ ] The pretty-printing exceeds the terminal width by a couple of columns #424
* [ ] Having to manually apply author and license to every definition is tedious
* [ ] `CreationDate` would be nice metadata to get added automatically to definitions
* [ ] Could we make it easier to launch the diff? (To avoid needing to copy paste)
  — what does this mean?
* [ ] Resolving a name conflict is really hard #1310

**Comment by aryairani** [comment]
Will create remaining individual issues
