### ISSUE TITLE
M2 Alpha Release Meta Ticket

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#1866]
We are prepping for a new major release of Unison which we're calling M2. After M2 will be possibly a few smaller point releases, then a feature complete beta, then general availability!

__Remaining todos:__

- [ ] All issues here: https://github.com/unisonweb/unison/milestones/M2
- [x] Update hero image for blog post
- [x] Fixup video on blog post
- [x] Rename `unisonweb/base` to `unisonweb/base_v1` and `unisonweb/base_v2` to `unisonweb/base`
- [x] Update blog post date to be today (update the directory and the front-matter)
- [x] Refresh Unison Share with latest base
- [x] Finalize release notes, which should include instructions on upgrading and also links to known issues that people are likely to encounter
- [x] Link to release notes in the GitHub release and the blog post
- [x] Update release notes on the GitHub release
    - [x] Make sure this includes instructions on updating V1 codebases
- [ ] Announce in `#contrib` and `#base-dev`, mention possible issue with WAL and link to issue. Also ask folks if they want their libraries listed on Unison Share.
- [ ] Merge M2 website to master
- [ ] Merge master to production
- [ ] Later announce in `#general` and twitter

**Comment by hojberg** [comment]
We can close this now right ? 🎉  😄

**Comment by aryairani** [comment]
Seems like.
