### ISSUE TITLE
codebase rehash migration megaticket

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#2471]
- [x] #2374 / #2100 
  - [x] #2460
    - [x] #2433
- [x] #2435
- [x] actually do the migration on codebase startup 
  - [x] figure out why this is happening #2332
  - [x] do the migration on pull?
  - [x] Don't re-migrate on every pull if no remote changes #2773 
- [x] regressions
  - [x] #2720
  - [x] #2719
  - [x] #2722
  - [x] #2733
  - [x] #2756 (fixed, but needs trunk to be merged back into topic/rehash-codebase)
- [x] fix hard coded hashes
  - [x] #2721
- [x] after successful migration, confirm inability to repro these:
  - [x] #2181
  - [x] #2122
  - [x] #2195 - Fixed in #2817
  - [x] #2011 - No valid reproduction ⚠️ ; probably fixed though since error is in getCycleLen
  - [x] #2495 
- [x] ensure these codebases migrate properly:
  - [x] base (https://github.com/unisonweb/base)
  - [x] distributed (https://github.com/unisonweb/distributed)
  - [x] nimbus (https://github.com/unisoncomputing/distributed)
  - [x] share (https://github.com/unisonweb/share)
- [x] merge #2635
  - [x] Ensure we use the Hashing.V2 module for parsing Causals within parser-typechecker.
  - [x] Tumble/salt hashing version number into all hashes.
- [x] verify the behavior of #2649
- [x] ~#2742~
- [x] Fix effects hashing #2777 
- [x] Decide about "a little too much hashing" in #2802  
- [x] Decide about #2787 
- [x] #2815
- [x] #2816
- [x] Disable logging messages, replace with progress bar of how many objects migrated/total to migrate.
- [x] (optional) Time and re-run migration over nimbus with an optimized build. (~2hrs on M1 mac)
- [x] #2831 -- We've decided to not do this as part of the migration.

Moving code around TODOs that would be nice to get to:
- [x] Extract hashing package from parser-typechecker (depends on Causal hashing TODO above)
- [x] New package to house hashing of codebase-sqlite structures
- [x] ~Move one-off 'hash DbBranch' into that package~
- [x] ~Migration package?~

More things:
- [x] ~Use HashTags newtypes in Unison.Hashing.V2 modules?~
- [x] Remove ConstructorType from Hashing.V2.Referent?
- [x] set up auto-pull from `base:v2` branch

From dogfooding:
- [x] #2840 - Decided this isn't critical to fix before the migration.
- [x] #2841
- [x] #2849 
- [x] #2865 (currently based on `trunk`)
