### ISSUE TITLE
M3 release checklist

### ISSUE THREAD

**Issue by pchiusano** [unisonweb/unison#2947]
Anything missing from this list?

- [x] merge rehash branch into trunk
- [x] dogfood trunk to make sure everything seems to be working fine
- [x] Garbage collect v1 hashes at end of migration? Is this done already? It's not done but we don't care for now.
- [x] https://github.com/unisonweb/unison/issues/2698 nevermind, this is not MVP for this release but would be nice to have
- [x] get to the bottom of https://github.com/unisonweb/unison/issues/2955
- [x] have UCM pull from base:v3
- [x] rename v2 branch to v3 branch in
  - [x] base
  - [x] distributed
  - [x] http
  - [x] share
- [x] base library changes, final signoff by @runarorama
  - [x] converted to v2 format, published at https://github.com/unisonweb/base/tree/v2
  - [x] fill in docs for terms/types referenced by front page
    - [x] `IO` type
    - [x] `Exception` type
    - [x] `printLine` function
    - [x] `Nat` type
    - [x] `Nat.+`
    - [x] `Nat.mod`
    - [ ] `Nat.==` 
  - [x] any important outstanding PRs merged
  - [x] README `Doc` for base, okay if more to do here, but a decent starting point is a must
  - [x] docs for `Map`
  - [x] docs for `Set`
- [x] distributed changes, final signoff by @pchiusano
  - [x] converted to v2 format, published at https://github.com/unisonweb/distributed/tree/v2
  - [x] Cody's [PR](https://github.com/unisonweb/distributed/issues/3) on Location and Scratch change
  - [x] any other misc changes?
  - [x] docs for stuff are linked from front page
    - [x] `Seq.map`
    - [x] `Seq.filter`
    - [x] `Seq.reduce`
    - [x] do an `_a2` release of distributed
    - [x] make sure the website links to the `_a2` release of distributed
    - [x] change website links to link to the root of share? or to individual projects? rather than always linking to the website project?
- [x] signoff from @aryairani team - are there any outstanding PRs or work that should get merged before release?
- [x] signoff from @hojberg on https://github.com/unisonweb/unison/pull/2946
- [x] new website is ready to go, final signoff by @hojberg and @rlmark  
  - [x] new front page
  - [x] Migrate website codebase to v2
  - [x] signoff from @rlmark on new docs
  - [x] signoff from @rlmark and @pchiusano on "Unison by example"
  - [x] blog ported
  - [x] special urls like /slack and /calendar are ported from unisonweb.org
  - [x] page urls are redirected correct from unisonweb.org to unison-lang.org
  - [x] Link to "Unison at a glance" from front page.
- [x] make sure all code linked on the front page examples has docs
- [x] @rlmark issue PR to change urls in welcome workflow 

  - [x] http library (@ceedubs: these are written and pushed to `git@github.com:stew/codebase:v3:.http.trunk`. We just need to update Share to include this.)
    - [x] `Response` type
    - [x] `Authority` type
    - [x] `Path.root` function on http
    - [x] `Path./` function on http
    - [x] `URI` type
    - [x] `https` function
    - [x] `Query.empty` function
    - [x] `Request.get` function
    - [x] `http.handler` function
- [x] migrate share to use v2 format. It can pull from v1 formats for now and will convert on the fly
  - [x] `base` update pull command to use the `v2` branch
  - [x] `distributed` update pull command to use the `v2` branch

- [x] migrate base to latest schema
- [x] migrate distributed to latest schema
- [x] migrate share to latest schema

## <a id="website"></a>Misc docs / website stuff

Misc docs stuff:

- [x] I’d like `/docs/fundamentals/abilities` to redirect to the starting point of the abilities content, probably the mental model doc. You can just rename the doc to “index” and it should just work.
- [x] @hojberg can we add a redirect from `/docs/abilities` to `/docs/fundamentals/abilities`
- [x] "abilities for the monadically inclined" should be moved to the end in the sidebar, after the FAQ (right now it appears second in the sidebar) and I'd replace its content with an "under construction" until @runarorama has something ready to go
- [x] http request example in "at a glance" doc doesn't have hyperlinked code
- [x] exception handling example in "at a glance" doc doesn't have hyperlinked code

Once all that's done, [usual release checklist steps](https://github.com/unisonweb/unison/blob/trunk/docs/release-steps.md).

**Comment by pchiusano** [comment]
Misc docs stuff:

- [ ] I’d like `/docs/fundamentals/abilities` to redirect to the starting point of the abilities content, probably the mental model doc. You can just rename the doc to “index” and it should just work.
- [ ] @hojberg can we add a redirect from `/docs/abilities` to `/docs/fundamentals/abilities`
- [ ] "abilities for the monadically inclined" should be moved to the end in the sidebar, after the FAQ (right now it appears second in the sidebar) and I'd replace its content with an "under construction" until @runarorama has something ready to go
- [ ] http request example in "at a glance" doc doesn't have hyperlinked code
- [ ] exception handling example in "at a glance" doc doesn't have hyperlinked code

**Comment by ceedubs** [comment]
> http request example in "at a glance" doc doesn't have hyperlinked code

@pchiusano @hojberg I believe that now that https://github.com/unisonweb/share/pull/38 is merged, this should be fixed once the rehashed version of share is deployed.

**Comment by pchiusano** [comment]
@ceedubs no, that's not the issue - the codeblock in question is just raw text, it's not that the links are broken (which yeah you are right should be fixed when the rehashed share is deployed).

**Comment by pchiusano** [comment]
@runarorama 

- [x] current base:v3 is missing releases.M2l, pull that from base:.releases._M2l (might be there in base:v2)

**Comment by aryairani** [comment]
Go team 🎉

**Comment by aryairani** [comment]
I captured the last remaining item as https://github.com/unisonweb/base/issues/90.
