### ISSUE TITLE
Q3 megaticket (previously "projects")

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#3338]
Please don't edit this description or these lists directly, but feel free to a) mark an item as done or b) move a blocked item to the unblocked section, or c) move a unblocked item to the in-progress section.. To contribute, add to the comments; we can discuss and then update these lists at the conclusion, and then hide the obsolete comments.

Projects will have some sort of unique project specifier, the exact format of which is TBD. For prototyping purposes, we can use a string newtype, and replace it with a GUID or slug or whatever more complex thing later.

**Things that are in progress:**
* [x] ex: make lists of tasks #3338 @aryairani
* [ ] (API and GUI implementation) Push history (basically reflog for share; can combine with #3271 for local)
* [x] https://github.com/unisonweb/unison/issues/3308 @mitchellwrosen 
* [x] definition summaries apis https://github.com/unisonweb/unison/issues/2175
* [x] understand history in the context of commands https://github.com/unisonweb/unison/issues/3355

**Things that are not blocked:**
* [ ] windows dev access https://github.com/unisonweb/unison/issues/3344
* [ ] Sketches #3339
* [ ] #3363
* [ ] (API nd implementation) global search, types, terms, doc text — make a call in terms of mock endpoints vs temporary/workaround implementation
* [ ] #3368
* [ ] definition diffs (2-way, 3-way)
* [ ] (GUI design) Project activity statistics (charts etc)
* [ ] (API and implementation) Codebase history
* [ ] Patches Revamp #3342
* [ ] Projects/Branches design #3341

**Things that can be worked on, but releasing, depends on Projects:**

* [ ] #3345
* [x] #3346
* [ ] (API and GUI implementation) Project activity statistics prototype (interesting charts about when and who and what is happening around your project)

**Things that are blocked:**
* [ ] ex: \<thing that is blocked\> (blocked on \<reason\>)
* [ ] Collaboration/permission settings for projects; add users who can view, push. (questions about the relationship between projects and branches and permissions. what does it mean to have push permission?)
* [ ] Proposals for PRs — e.g.: a PR is specifiers for two related namespaces + a `Doc` write-up describing the changes + (someday) code comments. (blocked on better understanding of projects vs branches, IMO -Arya)
* [ ] Proposals for Issues/Tickets. e.g.: issues are associated with a specific project branch (`trunk`/`main`, generally) (blocked on better understanding of projects vs branches, IMO -Arya)
* [ ] Account deletion (questions about what external things could be affected by someone's account deletion. can a project be deleted?)
* [ ] List releases of a project (questions about what a release is)
* [ ] Design proposals for Authorship stuff, displaying licenses (blocked on project design work)

Things for which it has not been determined whether they are blocked:
* tbd

**Comment by ChrisPenner** [comment]
- [ ] (Design, API, GUI, implementation) - Definition diffs

**Comment by hojberg** [comment]
API Tickets created after going through a couple of design iterations:

**Ready to be worked on:**
* https://github.com/unisonweb/unison/issues/3381
* https://github.com/unisonweb/unison/issues/3383
* https://github.com/unisonweb/unison/issues/3390
* https://github.com/unisonweb/unison/issues/3392
* https://github.com/unisonweb/unison/issues/3393

**Blocked by some notion of Projects existing:**
* https://github.com/unisonweb/unison/issues/3382
* https://github.com/unisonweb/unison/issues/3384
* https://github.com/unisonweb/unison/issues/3385
* https://github.com/unisonweb/unison/issues/3386
* https://github.com/unisonweb/unison/issues/3387
* https://github.com/unisonweb/unison/issues/3388
* https://github.com/unisonweb/unison/issues/3389

@aryairani let me know what you think.

**Comment by hojberg** [comment]
@aryairani is this ticket still worth keeping around?
