### ISSUE TITLE
Share Contributions (a.k.a. Pull Requests) Megaticket

### ISSUE THREAD

**Issue by ChrisPenner** [unisonweb/unison#3971]
### Functionality Goals

* Submit a PR for review
* Merge a PR (conflicts may be created, effectively just run UCM's merge command)
* Close a PR
* PR description & title
* PR status (Draft, Ready, Merged, Closed)
* List PRs (filter by status, author, contributor vs. core)
* PR timeline:
  * Opened at, closed at, merged at

#### Backend/APIs
* [x] Tables/schema for a contribution (title, description, created/updated, author, src branch, dest branch, status)
* [x] `GET /users/<handle>/projects/<slug>/contributions/123`  Get a contribution

```json
{ "contributionId": "123"
, "title": "Add FizzBuzz combinator."
, "description": "Adds fizzBuzz action to base so Unison programmers will pass all their job interviews."
, "status": "draft"
, "source": { "branch" : "@unison/base/@runarorama/feature"
            }
, "target": { "branch": "@unison/base/main"
            }
, "createdAt": "2023-06-02T14:23:18.505637Z"
, "updatedAt": "2023-06-02T14:23:18.505637Z"
, "authorHandle": "@runarorama"
}
```

* [x] `GET /users/<handle>/projects/<slug>/contributions?status=draft&kind=core`  List contributions

```json
[
    { "contributionId": "123"
    , "title": "Add FizzBuzz combinator."
    , "description": "Adds fizzBuzz action to base so Unison programmers will pass all their job interviews."
    , "status": "draft"
    , "source": { "branch" : "@unison/base/feature"
                }
    , "target": { "branch": "@unison/base/main"
                }
    , "createdAt": "2023-06-02T14:23:18.505637Z"
    , "updatedAt": "2023-06-02T14:23:18.505637Z"
    , "authorHandle": "@runarorama"
    }
]
```

* [x] `GET /users/<handle>/contributions` Get user contributions

```json
[
    { "contributionId": "123"
    , "title": "Add FizzBuzz combinator."
    , "description": "Adds fizzBuzz action to base so Unison programmers will pass all their job interviews."
    , "status": "draft"
    , "source": { "branch" : "@unison/base/feature"
                }
    , "target": { "branch": "@unison/base/main"
                }
    , "createdAt": "2023-06-02T14:23:18.505637Z"
    , "updatedAt": "2023-06-02T14:23:18.505637Z"
    , "authorHandle": "@runarorama"
    }
]
```

* [x] `PATCH /users/<handle>/projects/<slug>/contributions/123` Update status, title, description, source branch, target branch.

```json
{ "title": "New Title"
, "description": "New Description"
, "status": "ready"
, "source": { "branch" : "@unison/base/new-source"
            }
, "target": { "branch": "@unison/base/new-target"
            }
}
```

* [x] `GET /users/<handle>/projects/<slug>/contributions/123/timeline` Get the timeline for a contribution

```json
// Comments, reviews, and reactions will not be part of milestone 1.
{ "contributionId": "123"
, "activity": [
    { "kind": "comment"
    , "author": "@ChrisPenner"
    , "message": "This looks great!"
    , "reactions": {
        "🔥": ["@hojberg"]
      }
    , "timestamp": "2023-01-01T00:00:00Z"
    },
    { "kind": "review"
    , "author": "@aryairani"
    , "intent": "approval"
    , "message": "Let's merge this!"
    , "timestamp": "2023-01-01T00:00:00Z"
    , "reactions": {}
    }
    { "kind": "status_change"
    , "author": "@runarorama"
    , "status": "merged"
    , "timestamp": "2023-01-01T00:00:00Z"
    , "reactions": {
        "🚀": ["@hojberg"]
        }
      }
    }
  ]
}
```

* [ ] `POST /users/<handle>/projects/<slug>/contributions/123/merge` Merge the PR

#### Frontend

Milestone 2 (subject to change)
<details><summary>Expand</summary>

* Merge status (will conflicts be created); what will be the TODO result.
* Diff changes: namespace diffs and textual definition-diffs
* Change indicator (e.g. 7 definitions changed, 2 added, 1 removed)
* Conversation/comments, reactions
  * Definition-level comments
* timeline: hash changes

</details>

## Milestone 3 (subject to change)
<details><summary>Expand</summary>

* issues/bug reports (and linking between them)
* commit messages
* PR search
- Timeline: hash changes with commit messages and visual change indicators
- Timeline: fork sources with timestamps (forkedAt)
- Contribution search
- Notifications
- Rich comments
- Run tests before/after merging

</details>

![shapes](https://github.com/unisonweb/unison/assets/6439644/8ac4bf50-6635-4efd-9b21-d334f951a5a1)

**Comment by aryairani** [comment]
Let's add "test results after merging" somewhere; can be milestone 3 or whatever, and we can decide what that means.

**Comment by hojberg** [comment]
@ChrisPenner I think we can close this one right? 🎉

**Comment by ChrisPenner** [comment]
Sure, let's close it, we can track further updates separately.
