### ISSUE TITLE
Refactor for branchless

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#470]
__TODO:__
- [x] `patch <patch-id>` command (formerly `propagate`)
  - [x] implement `Output.PatchInvolvesExternalDependents`
- [x] implement `Output.BadDestinationBranch` (or replace/rename it?  what exactly is "bad" about it?)
- [x] trouble deleting conflicted term (#521)
- [x] command to merge builtins into a given branch?
- [x] command to copy external dependencies into a given branch?
- [x] `view` is not able to access old names, and (at least) if you've made a type-changing edit, you'll arguably want to see old names when viewing a dependent. (#535)
- [x] `todo` incorrectly reporting nothing to do after updating one element of a cycle.
- [x] `update` should probably require that all of the cycle be updated?
- [x] `delete.path` complaining about deleting dependencies of stuff it's deleting? #526
- [x] add `delete.patch`
  - [x] `BranchUtil.makeDeletePatch`
- [x] add `rename.patch`
  - [x] `BranchUtil.makeAddPatch`

__Later:__
- [x] output after completing an `update` should probably be different from before an `update`, to indicate that it's happened?
- [x] `view foo bar` only shows `bar` when `foo` and `bar` are the same, but you don't know why
- [x] `unlink` command fails spuriously
- [x] Add a version of `update` that doesn't need/use a patch.
- [x] When updating a thing which is metadata for X, update X's metadata to point to new metadata.
- [x] `todo` currently requires a `patch` argument, but you can pass a fake one if you're just interested in name conflict todos.
- [x] Handle external branch file updates (see todo in HandleInput.hs)
- [x] To render a var of kind `Ref` in the prettyprinter, can lookup the ref
- [x] In `HandleInput` for `update`, should raise an error term or type edits contains a loop
- [x] `Branch.stepManyAt/M` needs smarter implementation
- [x] Bug: when a type can't be added for whatever reason, its constructor terms still get added anyway.
- [x] type autocomplete provider (in `InputPatterns2`)
- [x] term autocomplete provider (in `InputPatterns2`)
- [x] patchPathArg autocomplete provider (in `InputPatterns2`)
- [x] Codebase repo format changes to handle multiple definitions with the same hash, see discussion in [this doc](https://github.com/unisonweb/unison/blob/wip/branchless/docs/repoformats/v0-DRAFT.markdown).
- [x] add `-s recursive -X ours` to various merge commands, see #523 for background

__Once everything works:__

- [x] Update Parser to use `Names2`
  - [x] `Unison.Test.Common.t`, `tm`
- [x] Delete `Names`, rename `Names2` to `Names`
- [x] Delete `Codebase`, rename `Codebase2` to `Codebase`
- [x] Delete `FileCodebase`, rename `FileCodebase2` to `FileCodebase`
- [x] Delete `Builtin`, rename `Builtin2` to `Builtin`
- [x] Delete `CommandLine.Main`, rename `CommandLine.Main2` to `CommandLine.Main`
- [x] Delete `unison/Main`, rename `unison2/Main` to `unison/Main`
- [x] Delete `Actions` (now `HandleInput`)
- [x] Delete `Editor` (now `HandleCommand`)
- [x] Delete `OutputMessages`, rename `OutputMessages2` to `OutputMessages`

__Maybe later:__
- [x] distinguish codebase names from .u file names when pretty-printing decompiled/evaluated terms (#524)
- [x] support a version of `update` that doesn't require or update a patch
- [x] make fuzzy `find` less fuzzy
- [x] `Typechecked` output could use `SlurpResult` to preview what would happen in the event of an `add` or `update`. Just modify `OutputMessages2.hs` `Typechecked` case.
- [x] multiple undos in rapid succession generate an external branch event
- [x] should have a way to delete multiple definitions at once (especially mutually dependent definitions).  A workaround is to rename them into a Trash branch  or similar and then delete the Trash branch.
- [x] `view` should display more than empty lines when there is no matching definition to view.
- [x] `rename.type Optional Maybe` should rename `Optional.Some` to `Maybe.Some`, etc
- [x] Allow moving the root branch to a child of itself (e.g. in preparation to fork what had been the root)
- [x] 3-way merge for `Branch` (look back 1 step at a time on both sides to find a match, only 2x worse than optimal) - impact of not having this would be that if there are concurrent edits and deletes to the same package, the deletes will get undeleted! (Doesn't require changing repo format, so easy to alter merge strategy later)
- [x] 3-way merge for edits
- [x] Update prettyprinter to use Names directly
- [x] Parser should support hash-qualified identifiers (when viewing a definition with conflicted dependencies, would be nice if that definition parses)
- [x] `view` should show aliases
- [x] `HashQualified.hashLength : Set Reference -> Int` to compute the number of base 58 characters that must be used to disambiguate among all the given references (can hard code 8 for now, but should compute `1 + longest common prefix`)

__Bonus:__
- [x] `undo` should print some nice message about what was undone, but diffing the two heads

__Cleanup:__
- [x] Get rid of `PrettyPrintEnv` and just use `Names` directly.  (Arya added a `Names.unionLeft`.)
- [x] Don't use `Var` for builtin term and type names in `Builtin2`
- [x] Delete `DataDeclaration.dataCtorTerms`, seems useless
- [x] Take a look at `Names` vs `Names0` usage and decide if we need both, and/or rename as appropriate
- [x] Take a look at `HashQualified` vs `HashQualified'` usage and decide if we need both, and/or rename as appropriate
- [x] Take a look at `AnnotatedTerm` vs `Term`, `AnnotatedType` vs `Type`; decide if we need both and rename as appropriate
- [x] Rethink runtime interface - does it need a full `UnisonFile`?

__Done:__

- [x] #501 (Git syncing)
- [x] `view.patch <patch-id>` command
  - [x] load more from history into `Names0` for output message
- [x] implement `find.patch,` as patches are otherwise invisible
- [x] `update <patch-id>` command
  - [x] fill in `HandleInput.doSlurpUpdates`
- [x] `todo <patch-id>` command
  - [x] update `Input.TodoI`
  - [x] fill in `HandleInput.TodoI`
  - [x] fill in `HandleInput.checkTodo`
    - [x] fill in `nameConflicts`
    - [x] fill in `editConflicts`
  - [x] update `Output.TodoOutput`
  - [x] update `OutputMessages.todoOutput`
    - [x] update `renderEditConflicts` to get conflicts in `Patch` instead of `Branch`
    - [x] fill in `removeEditConflicts` to filter the `Patch` passed to `renderNameConflicts`
- [x] fix `view` to prefer a name the user specified, as opposed to a random alias
- [x] fix `view` to use names relative to current path, not root
  - [x] fill in `queryPPE`
- [x] Watch expression cache should be ported to `Codebase2`, can mirror `Codebase`
- [x] evaluation working end to end
- [x] typechecking
- [x] `delete.type` doesn't work, `delete.type IO` doesn't complain.
- [x] `delete.term` doesn't work, `delete.term IO.putText` succeeds although it is needed by `IO.printLine`.
- [x] `delete` doesn't work, reports spurious failures with incorrect `failed` and `failedDependents`. Try `delete.term Nat.+`.
- [x] `delete.{term,type,branch}` bombs on rendering output, need to update `OutputMessages2`
- [x] `rename.{term,type}` fails to delete old name, and is missing output message for when the new name is already taken
- [x] `undo` command
- [x] `rename.branch` end to end
- [x] Aliases of duplicate definitions are listed separately in OutputMessages2 after typechecking.  Don't remove the aliases from the SlurpResult, but don't display those particular alias lines either.
- [x] Define `Path.parsePath` in terms of Lexer `wordyId` and/or `symbolyId`
- [x] Update https://github.com/unisonweb/unison/tree/wip/branchless/docs/repoformats to say how `dependents` directory gets updated
- [x] `alias.type` end to end
- [x] when `undo` fails, should say why (can't move past a merge OR nothing more to undo)
- [x] Add some indicator to the prompt when in an empty branch
- [x] should sync at least `watches/test` directory when Git syncing (if the file `watches/test/<hash>.ub` exists for some `<hash>` in the branch, can copy that file over)
- [x] `test <path>` command
  - [x] Metadata implementation (`link`, `unlink`, `links`) commands
- [x] branchPathArg autocomplete provider (in `InputPatterns2`)
