### ISSUE TITLE
jit release checklist

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#4843]
- [x] #4841
- [x] #4846 
- [x] confirm CI test suite exercises relevant FFI bindings
- [ ] pass nimbus integration tests
- [ ] brainstorm some other tests?
- [ ] restore the `run.native` and `compile.native` commands to visible 
- [ ] Nix derivations
- [x] include libb2 on mac? 
- [ ] figure out why bundled libcrypto for mac is passed over in favor of incompatible system lib
- [x] fix startup wrappers to put quotes around ucm, in case startup path has spaces etc
- [x] move `unison-src/builtin-tests/thread-killed-typeLink-test.u` to concurrency-tests now that JIT supports type links?
- [ ] jit test suite failures detectable in CI
- [ ] look into reducing latency for `run.native`

**Comment by ceedubs** [comment]
@aryairani it's not a requirement for release, but I'd also love if you could help me understand what is needed for the jit runtime so I can make it available in the Nix derivation for ucm (maybe as an option?).

**Comment by aryairani** [comment]
@ceedubs Sure, I added it to the list and we can chat. Maybe taking a look at the updated Dockerfile together would be helpful, I just merged some changes about it there.
