### ISSUE TITLE
Decide on a way to represent and correctly render current vs historical names.

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#556]
- [x] allow `.` as an identifier
- [x] apply to `delete` (#550)
  - [x] 💥`DeleteBranchI`
  - [x] 💥`DeleteTypeI`
  - [x] 💥`DeleteTermI`
- [x] 💥`NamesI`
- [x] 💥`LinkI`
- [x] 💥`UnlinkI` -- should be straightforward since it just outputs "Done"
- [x] 💥`LinksI`
  - [x] HandleCommand.hs `ParseType`?
  - [x] uncomment / fix `HandleInput.parseType`?
  - [x] `HandleInput.lexedSource`?
- [x] 💥`TestI`
- [x] 💥`SearchByNameI`...
- [x] Look into parse error in `Base.u`
- [x] local constructor names aren't shown in type errors (#566)
- [x] `Type.bindSomeNames` which doesn't fail, leaves variables free if not found in the environment, use that to substitute external names into the constructor types of the parsed data declarations, before hashing those declarations. Update `FileParser.file` and/or `environmentFor`.
- [x] `AddI`
- [x] `UpdateI`
- [x] `TodoI`
- [x] `PatchI`
- [x] `ListEditsI`
- [x] apply to `view` (#549)
  - [x] `ShowDefinitionI`
- [x] `undefined` in `FileParsers.synthesizeFile` needs to embed name resolution errors into the `Result` monad after the `Term.bindNames` call
- [x] `HandleInput.withFile` call immediately before invoking `Typecheck` command needs to
  - [x] lex the file, pull out all the hash-qualified tokens then monadically load from history a `Names0` 
  - [x] 💥 and a constructorType function with info related to these HQs. 
- [x] `printNoteWithSource _env _s   (NameResolutionFailures _es) = undefined` in `PrintError`
- [x] uncomment / fix `Common.t`, `tm`
- [x] `use` parser should return a `[(v,v)]` and just do variable substitution as before
- [x] 💥 `TermParser.block'`
- [x] Handle `ResolutionFailures` in PrintError.hs

![image](https://user-images.githubusercontent.com/538571/60633851-98976200-9dda-11e9-8dc3-7d85915f33e8.png)

**Comment by aryairani** [comment]
Gonna try seeing how far I can get with a `Names2.Names' (Name, IsHistorical)` where
`data IsHistorical = Historical | Current`
