### ISSUE TITLE
Unison on Windows megaticket

### ISSUE THREAD

**Issue by aryairani** [unisonweb/unison#598]
- [x] #2913
  - [x] #2937 
  - [x] #2917
  - [x] #2938 
  - [x] #2924 
  - [x] #2940
  - [x] #2941
  - [x] #2936 
- [x] #2939
- [x] fix git launching #2900, #2914
- [x] #2926
- [x] #2933
- [x] #2934 
- [x] ~~Use `git config --global core.longpaths true` to enable longpath support in windows git.~~ (No longer relevant with sqlite codebase)
- [x] Will `less` work for paging in windows? 
  - Yes, a compatible `less` is on the `$PATH` provided by `stack exec`
- [x] use base-4.12 for improved windows file support (#827)
- [x] `unix` package (#912) blocks testing on `master`; using 3db04038 until #1131. longer term fix is win64 branch without #912.
- [x] something seems broken wrt .u file watching.  (.config file watching seems ok, however)
  - commenting out the watcher allows ucm to display the command prompt and accept commands
  - [x] debug watcher or sidestep it with manual load command.
- [x] `load` command isn't present in 3db04038 (whoops), but with the file watchers stripped out, I can get to the ucm prompt!
- [x] `pull` yields a generic error, though external `git` can access the requested repo.  What's the real failure reason? #1870

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/61849611-8f376d80-ae4d-11e9-9ec1-2d3f90951192.png)
getting better...

This is with Windows Terminal (Preview) https://www.microsoft.com/store/apps/9n0dx20hk701

**Comment by aryairani** [comment]
With respect to the hardcoded `/`, I have updated the code, but it doesn't seem to be taking effect...  I just wiped `.stack-work`, and fingers are crossed.

**Comment by aryairani** [comment]
The issue was one of using `(System.FilePath.Posix.</>)` rather than `(System.FilePath.</>)`.

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/61917199-a9258e80-aee7-11e9-8196-1a1413f91e0d.png)
☝️ latest is this, still no initial branch head?

**Comment by pchiusano** [comment]
Try blowing away you cache and you .unison, then pull again from unisonbase. Not sure where cache located on windows, look for Xdg location windows.

**Comment by pchiusano** [comment]
I verified that current unisonbase is legit from a clean pull so you shouldn’t see this if you clear your caches and try again.

**Comment by pchiusano** [comment]
Still issues with max file path length, is that right @aryairani?

**Comment by aryairani** [comment]
Yes, I believe so.  Open question is whether the Windows 10 registry trick + being careful to only access files on disk by absolute path will do the right thing with existing Haskell file IO libs.  I started working on this; no success yet but also haven’t been exhaustive yet.

**Comment by aryairani** [comment]
Re  https://github.com/unisonweb/unison/issues/598#issuecomment-515266534

I haven’t gotten as far as a Unison`pull` yet.

**Comment by pchiusano** [comment]
https://hub.zhox.com/posts/bypassing-max_path-limit-on-windows/ possibly relevant

Arya also came up with the idea of just having a `ZippedFileCodebase` implementation which is basically a `FileCodebase` backed by a .zip file. We'd just need a Haskell zip file library that can do decompression on demand of individual files. And there might be some interesting cases with `push` and `pull` commands.

**Comment by aryairani** [comment]
If some windows user could try even git cloning unisonbase that would be a good starting point.  I am also still holding out hope that there’s some haskell file io library that we can make just work under windows.  Windows supports the long paths, it’s just a matter of calling the right apis from haskell.

**Comment by aryairani** [comment]
Lol yes that link is relevant.

**Comment by aryairani** [comment]
I think that link is saying that the Haskell _compiler_ will support long paths as of 8.10+, but we don't care about that.  We want _our_ Haskell _program_ to support long paths.

**Comment by aryairani** [comment]
> there might be some interesting cases with `push` and `pull` commands.

Confirmed git version 2.22.0.windows.1 can clone unisonbase if and only if the `core.longpaths` flag is set to `true`. https://stackoverflow.com/questions/22575662/filename-too-long-in-git-for-windows

**Comment by aryairani** [comment]
Current status:
![image](https://user-images.githubusercontent.com/538571/65704450-9567e700-e054-11e9-897b-f6dcb06640e8.png)

**Comment by aryairani** [comment]
![image](https://user-images.githubusercontent.com/538571/65704657-ed9ee900-e054-11e9-8570-e66becee2dc6.png)

Windows Terminal ☝️ 

Clues in system trace? Register for file notification, followed by two threads exits & a seemingly hung ucm.

**Comment by aryairani** [comment]
If I try to create a codebase in Windows without `\\?\`, I get this error:
```
unison.EXE: C:\Users\x1\unison\.unison\v1\type-mentions-index\#42rq4adimjcnkuq8tm8i6ph7vsnqv75lu7jnqbho6rpn681t6dojn6c1t8dntjvlkstf9qo09ick6d8vpfr507ebee60ik8dbpp50u0\#5isltsdct9fhcrvud9gju8u0l9g0k9d3lelkksea3a8jdgs1uqrs5mm9p7bajj84gg8l9c9jgv9honakghmkb28fucoeb2p4v9ukmu8#d0: openFile: does not exist (No such file or directory)
```
but procmon doesn't show any attempt to open that file.

**Comment by aryairani** [comment]
Bleh https://gitlab.haskell.org/ghc/ghc/issues/13373

**Comment by aryairani** [comment]
It's in [base-4.12.0.0](http://hackage.haskell.org/package/base-4.12.0.0/src/cbits/fs.c) 🎉  but not in base-4.11.1.0.

**Comment by cup** [comment]
https://github.com/unisonweb/unison/issues/828

**Comment by jneira** [comment]
@aryairani maybe i could spend some time trying to improve windows support as part of ZuriHac, is there some area where do you think is interesting to start to test/improve?

(i've built the project locally with cabal and the build was succesful, i guess tests will fail)

**Comment by aryairani** [comment]
@jneira That would be great! I was just wishing I knew of someone who could do that.

The first thing I would like to understand is #1870, and then depending on how much time you have to devote to it, we could continue trying to sort out further issues as they are revealed.

**Comment by aryairani** [comment]
Opened draft pr #2913 to track build status.

**Comment by ChrisPenner** [comment]
All done 👍🏼
